# Generated by Django 5.1.7 on 2025-03-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Poste')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('endereco', models.CharField(default='Não disponível', max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(default='Não disponível', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='Não disponível', max_length=100, verbose_name='Estado')),
                ('pais', models.CharField(default='Não disponível', max_length=100, verbose_name='País')),
                ('foto', models.TextField(blank=True, null=True, verbose_name='Foto (Base64)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
    ]
