# Generated by Django 5.1.7 on 2025-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='defeito',
            field=models.BooleanField(default=False, verbose_name='Possui Defeito?'),
        ),
    ]
